"""empty message

Revision ID: 573e579c1d1b
Revises: 
Create Date: 2021-05-09 21:59:04.617135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '573e579c1d1b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('v1_1_CaseSolutions',
    sa.Column('Id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('CaseId', sa.String(length=255), nullable=True),
    sa.Column('Origin', sa.String(length=255), nullable=True),
    sa.Column('KnowledgeProviderPathCount', sa.SmallInteger(), nullable=True),
    sa.Column('KnowledgeProviderPath1Name', sa.String(length=255), nullable=True),
    sa.Column('KnowledgeProviderPath2Name', sa.String(length=255), nullable=True),
    sa.Column('Node1Path1Category', sa.String(length=255), nullable=True),
    sa.Column('Node1Path1Type', sa.String(length=255), nullable=True),
    sa.Column('Node1Path1Reference', sa.String(length=255), nullable=True),
    sa.Column('Node2Path1Category', sa.String(length=255), nullable=True),
    sa.Column('Node2Path1Type', sa.String(length=255), nullable=True),
    sa.Column('Node2Path1Reference', sa.String(length=255), nullable=True),
    sa.Column('Edge1Path1Predicate', sa.String(length=255), nullable=True),
    sa.Column('Edge1Path1Ends', sa.String(length=255), nullable=True),
    sa.Column('Edge1Path1Reference', sa.String(length=255), nullable=True),
    sa.Column('Node1Path2Category', sa.String(length=255), nullable=True),
    sa.Column('Node1Path2Type', sa.String(length=255), nullable=True),
    sa.Column('Node1Path2Reference', sa.String(length=255), nullable=True),
    sa.Column('Node2Path2Category', sa.String(length=255), nullable=True),
    sa.Column('Node2Path2Type', sa.String(length=255), nullable=True),
    sa.Column('Node2Path2Reference', sa.String(length=255), nullable=True),
    sa.Column('Edge1Path2Predicate', sa.String(length=255), nullable=True),
    sa.Column('Edge1Path2Ends', sa.String(length=255), nullable=True),
    sa.Column('Edge1Path2Reference', sa.String(length=255), nullable=True),
    sa.CheckConstraint('\n            (\n                "KnowledgeProviderPathCount" = 1 and\n                "KnowledgeProviderPath2Name" is null and\n                "Node1Path2Category" is null and\n                "Node1Path2Type" is null and\n                "Node1Path2Reference" is null and\n                "Node2Path2Category" is null and\n                "Node2Path2Type" is null and\n                "Node2Path2Reference" is null and\n                "Edge1Path2Predicate" is null and\n                "Edge1Path2Ends" is null and\n                "Edge1Path2Reference" is null\n            ) OR (\n                "KnowledgeProviderPathCount" = 2 and\n                "KnowledgeProviderPath2Name" is not null and\n                "Node1Path2Category" is not null and\n                "Node1Path2Type" is not null and\n                "Node1Path2Reference" is not null and\n                "Node2Path2Category" is not null and\n                "Node2Path2Type" is not null and\n                "Node2Path2Reference" is not null and\n                "Edge1Path2Predicate" is not null and\n                "Edge1Path2Ends" is not null and\n                "Edge1Path2Reference" is not null and\n                "Node2Path1Category" = "Node1Path2Category"\n            )\n            ', name='chk_v1_1_CaseSolutions_KnowledgeProviderPathCount'),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('v1_1_GlobalSimilarity',
    sa.Column('Id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('Subject', sa.String(length=255), nullable=True),
    sa.Column('Object', sa.String(length=255), nullable=True),
    sa.Column('Predicate', sa.String(length=255), nullable=True),
    sa.Column('CaseId', sa.String(length=255), nullable=True),
    sa.Column('CaseValue', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index('uk_v1_1_GlobalSimilarity_Subject_Object_Predicate_CaseId', 'v1_1_GlobalSimilarity', ['Subject', 'Object', 'Predicate', 'CaseId'], unique=True)
    op.create_table('v1_1_KnowledgeProviders',
    sa.Column('Id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('Name', sa.String(length=255), nullable=True),
    sa.Column('Url', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index('uk_v1_1_KnowledgeProviders_Name', 'v1_1_KnowledgeProviders', ['Name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uk_v1_1_KnowledgeProviders_Name', table_name='v1_1_KnowledgeProviders')
    op.drop_table('v1_1_KnowledgeProviders')
    op.drop_index('uk_v1_1_GlobalSimilarity_Subject_Object_Predicate_CaseId', table_name='v1_1_GlobalSimilarity')
    op.drop_table('v1_1_GlobalSimilarity')
    op.drop_table('v1_1_CaseSolutions')
    # ### end Alembic commands ###
