"""not null

Revision ID: 707b48cb1adf
Revises: 573e579c1d1b
Create Date: 2021-05-16 22:20:05.001081

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '707b48cb1adf'
down_revision = '573e579c1d1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('v1_1_CaseSolutions', 'CaseId',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('v1_1_CaseSolutions', 'Origin',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('v1_1_CaseSolutions', 'KnowledgeProviderPathCount',
               existing_type=sa.SMALLINT(),
               nullable=False)
    op.alter_column('v1_1_CaseSolutions', 'KnowledgeProviderPath1Name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('v1_1_CaseSolutions', 'Node1Path1Category',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('v1_1_CaseSolutions', 'Node1Path1Type',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('v1_1_CaseSolutions', 'Node1Path1Reference',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('v1_1_CaseSolutions', 'Node2Path1Category',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('v1_1_CaseSolutions', 'Node2Path1Type',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('v1_1_CaseSolutions', 'Node2Path1Reference',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('v1_1_CaseSolutions', 'Edge1Path1Predicate',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('v1_1_CaseSolutions', 'Edge1Path1Ends',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('v1_1_CaseSolutions', 'Edge1Path1Reference',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('v1_1_GlobalSimilarity', 'Subject',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('v1_1_GlobalSimilarity', 'Object',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('v1_1_GlobalSimilarity', 'Predicate',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('v1_1_GlobalSimilarity', 'CaseId',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('v1_1_GlobalSimilarity', 'CaseValue',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('v1_1_KnowledgeProviders', 'Name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('v1_1_KnowledgeProviders', 'Url',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('v1_1_KnowledgeProviders', 'Url',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('v1_1_KnowledgeProviders', 'Name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('v1_1_GlobalSimilarity', 'CaseValue',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('v1_1_GlobalSimilarity', 'CaseId',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('v1_1_GlobalSimilarity', 'Predicate',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('v1_1_GlobalSimilarity', 'Object',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('v1_1_GlobalSimilarity', 'Subject',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('v1_1_CaseSolutions', 'Edge1Path1Reference',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('v1_1_CaseSolutions', 'Edge1Path1Ends',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('v1_1_CaseSolutions', 'Edge1Path1Predicate',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('v1_1_CaseSolutions', 'Node2Path1Reference',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('v1_1_CaseSolutions', 'Node2Path1Type',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('v1_1_CaseSolutions', 'Node2Path1Category',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('v1_1_CaseSolutions', 'Node1Path1Reference',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('v1_1_CaseSolutions', 'Node1Path1Type',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('v1_1_CaseSolutions', 'Node1Path1Category',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('v1_1_CaseSolutions', 'KnowledgeProviderPath1Name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('v1_1_CaseSolutions', 'KnowledgeProviderPathCount',
               existing_type=sa.SMALLINT(),
               nullable=True)
    op.alter_column('v1_1_CaseSolutions', 'Origin',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('v1_1_CaseSolutions', 'CaseId',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
